In [1]:
import pandas as pd

In [8]:
df =pd.read_csv('PokemonData.csv')

In [9]:
df.head()

,Num,Name,Type1,Type2,HP,Attack,Defense,SpAtk,SpDef,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [13]:
df1=pd.read_csv('pokemon_data.txt', delimiter='\t')
df1.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [15]:
#GETTING HEADERS or columns

df.columns

Index(['Num', 'Name', 'Type1', 'Type2', 'HP', 'Attack', 'Defense', 'SpAtk',
       'SpDef', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [18]:
# GET SPECIFIC COLUMNS OR COLUMN

df['Name'][0:5]

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [19]:
df[['Name', 'HP', 'Speed']]

                      Name  HP  Speed
0                Bulbasaur  45     45
1                  Ivysaur  60     60
2                 Venusaur  80     80
3    VenusaurMega Venusaur  80     80
4               Charmander  39     65
..                     ...  ..    ...
795                Diancie  50     50
796    DiancieMega Diancie  50    110
797    HoopaHoopa Confined  80     70
798     HoopaHoopa Unbound  80     80
799              Volcanion  80     70

[800 rows x 3 columns]

In [20]:
#GET SPECIFIC ROW OR ROWS

df.iloc[1]

Num                 2
Name          Ivysaur
Type1           Grass
Type2          Poison
HP                 60
Attack             62
Defense            63
SpAtk              80
SpDef              80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [21]:
df.iloc[1:4]

,Num,Name,Type1,Type2,HP,Attack,Defense,SpAtk,SpDef,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False

In [23]:
# GET SPECIFIC ELEMENT IN A ROW 

df.iloc[3,1]

'VenusaurMega Venusaur'

In [35]:
# ITERATING THROUGH ROWS IN A DATAFRAME

'''for index, row in df.iterrows():
    print(index, row)'''
    
# ITERATE THROUGH ROWS FOR SPECIFIC ELEMENT OR COLUMN

for index, row in df.iterrows():
    #print(index, row['Type2'])
    print(row["Name"])

Bulbasaur
Ivysaur
Venusaur
VenusaurMega Venusaur
Charmander
Charmeleon
Charizard
CharizardMega Charizard X
CharizardMega Charizard Y
Squirtle
Wartortle
Blastoise
BlastoiseMega Blastoise
Caterpie
Metapod
Butterfree
Weedle
Kakuna
Beedrill
BeedrillMega Beedrill
Pidgey
Pidgeotto
Pidgeot
PidgeotMega Pidgeot
Rattata
Raticate
Spearow
Fearow
Ekans
Arbok
Pikachu
Raichu
Sandshrew
Sandslash
Nidoranâ™€
Nidorina
Nidoqueen
Nidoranâ™‚
Nidorino
Nidoking
Clefairy
Clefable
Vulpix
Ninetales
Jigglypuff
Wigglytuff
Zubat
Golbat
Oddish
Gloom
Vileplume
Paras
Parasect
Venonat
Venomoth
Diglett
Dugtrio
Meowth
Persian
Psyduck
Golduck
Mankey
Primeape
Growlithe
Arcanine
Poliwag
Poliwhirl
Poliwrath
Abra
Kadabra
Alakazam
AlakazamMega Alakazam
Machop
Machoke
Machamp
Bellsprout
Weepinbell
Victreebel
Tentacool
Tentacruel
Geodude
Graveler
Golem
Ponyta
Rapidash
Slowpoke
Slowbro
SlowbroMega Slowbro
Magnemite
Magneton
Farfetch'd
Doduo
Dodrio
Seel
Dewgong
Grimer
Muk
Shellder
Cloyster
Gastly
Haunter
Gengar
GengarMega Gengar
Onix
Drowzee
Hypno
Krabby
Kingler
Voltorb
Electrode
Exeggcute
Exeggutor
Cubone
Marowak
Hitmonlee
Hitmonchan
Lickitung
Koffing
Weezing
Rhyhorn
Rhydon
Chansey
Tangela
Kangaskhan
KangaskhanMega Kangaskhan
Horsea
Seadra
Goldeen
Seaking
Staryu
Starmie
Mr. Mime
Scyther
Jynx
Electabuzz
Magmar
Pinsir
PinsirMega Pinsir
Tauros
Magikarp
Gyarados
GyaradosMega Gyarados
Lapras
Ditto
Eevee
Vaporeon
Jolteon
Flareon
Porygon
Omanyte
Omastar
Kabuto
Kabutops
Aerodactyl
AerodactylMega Aerodactyl
Snorlax
Articuno
Zapdos
Moltres
Dratini
Dragonair
Dragonite
Mewtwo
MewtwoMega Mewtwo X
MewtwoMega Mewtwo Y
Mew
Chikorita
Bayleef
Meganium
Cyndaquil
Quilava
Typhlosion
Totodile
Croconaw
Feraligatr
Sentret
Furret
Hoothoot
Noctowl
Ledyba
Ledian
Spinarak
Ariados
Crobat
Chinchou
Lanturn
Pichu
Cleffa
Igglybuff
Togepi
Togetic
Natu
Xatu
Mareep
Flaaffy
Ampharos
AmpharosMega Ampharos
Bellossom
Marill
Azumarill
Sudowoodo
Politoed
Hoppip
Skiploom
Jumpluff
Aipom
Sunkern
Sunflora
Yanma
Wooper
Quagsire
Espeon
Umbreon
Murkrow
Slowking
Misdreavus
Unown
Wobbuffet
Girafarig
Pineco
Forretress
Dunsparce
Gligar
Steelix
SteelixMega Steelix
Snubbull
Granbull
Qwilfish
Scizor
ScizorMega Scizor
Shuckle
Heracross
HeracrossMega Heracross
Sneasel
Teddiursa
Ursaring
Slugma
Magcargo
Swinub
Piloswine
Corsola
Remoraid
Octillery
Delibird
Mantine
Skarmory
Houndour
Houndoom
HoundoomMega Houndoom
Kingdra
Phanpy
Donphan
Porygon2
Stantler
Smeargle
Tyrogue
Hitmontop
Smoochum
Elekid
Magby
Miltank
Blissey
Raikou
Entei
Suicune
Larvitar
Pupitar
Tyranitar
TyranitarMega Tyranitar
Lugia
Ho-oh
Celebi
Treecko
Grovyle
Sceptile
SceptileMega Sceptile
Torchic
Combusken
Blaziken
BlazikenMega Blaziken
Mudkip
Marshtomp
Swampert
SwampertMega Swampert
Poochyena
Mightyena
Zigzagoon
Linoone
Wurmple
Silcoon
Beautifly
Cascoon
Dustox
Lotad
Lombre
Ludicolo
Seedot
Nuzleaf
Shiftry
Taillow
Swellow
Wingull
Pelipper
Ralts
Kirlia
Gardevoir
GardevoirMega Gardevoir
Surskit
Masquerain
Shroomish
Breloom
Slakoth
Vigoroth
Slaking
Nincada
Ninjask
Shedinja
Whismur
Loudred
Exploud
Makuhita
Hariyama
Azurill
Nosepass
Skitty
Delcatty
Sableye
SableyeMega Sableye
Mawile
MawileMega Mawile
Aron
Lairon
Aggron
AggronMega Aggron
Meditite
Medicham
MedichamMega Medicham
Electrike
Manectric
ManectricMega Manectric
Plusle
Minun
Volbeat
Illumise
Roselia
Gulpin
Swalot
Carvanha
Sharpedo
SharpedoMega Sharpedo
Wailmer
Wailord
Numel
Camerupt
CameruptMega Camerupt
Torkoal
Spoink
Grumpig
Spinda
Trapinch
Vibrava
Flygon
Cacnea
Cacturne
Swablu
Altaria
AltariaMega Altaria
Zangoose
Seviper
Lunatone
Solrock
Barboach
Whiscash
Corphish
Crawdaunt
Baltoy
Claydol
Lileep
Cradily
Anorith
Armaldo
Feebas
Milotic
Castform
Kecleon
Shuppet
Banette
BanetteMega Banette
Duskull
Dusclops
Tropius
Chimecho
Absol
AbsolMega Absol
Wynaut
Snorunt
Glalie
GlalieMega Glalie
Spheal
Sealeo
Walrein
Clamperl
Huntail
Gorebyss
Relicanth
Luvdisc
Bagon
Shelgon
Salamence
SalamenceMega Salamence
Beldum
Metang
Metagross
MetagrossMega Metagross
Regirock
Regice
Registeel
Latias
LatiasMega Latias
Latios
LatiosMega Latios
Kyogre
KyogrePrimal Kyogre
Groudon
GroudonPrimal Groudon
Rayquaza
RayquazaMega Rayquaza
Jirachi
DeoxysNormal Forme
DeoxysAttack Forme
DeoxysDefense Forme
DeoxysSpeed Forme
Turtwig
Grotle
Torterra
Chimchar
Monferno
Infernape
Piplup
Prinplup
Empoleon
Starly
Staravia
Staraptor
Bidoof
Bibarel
Kricketot
Kricketune
Shinx
Luxio
Luxray
Budew
Roserade
Cranidos
Rampardos
Shieldon
Bastiodon
Burmy
WormadamPlant Cloak
WormadamSandy Cloak
WormadamTrash Cloak
Mothim
Combee
Vespiquen
Pachirisu
Buizel
Floatzel
Cherubi
Cherrim
Shellos
Gastrodon
Ambipom
Drifloon
Drifblim
Buneary
Lopunny
LopunnyMega Lopunny
Mismagius
Honchkrow
Glameow
Purugly
Chingling
Stunky
Skuntank
Bronzor
Bronzong
Bonsly
Mime Jr.
Happiny
Chatot
Spiritomb
Gible
Gabite
Garchomp
GarchompMega Garchomp
Munchlax
Riolu
Lucario
LucarioMega Lucario
Hippopotas
Hippowdon
Skorupi
Drapion
Croagunk
Toxicroak
Carnivine
Finneon
Lumineon
Mantyke
Snover
Abomasnow
AbomasnowMega Abomasnow
Weavile
Magnezone
Lickilicky
Rhyperior
Tangrowth
Electivire
Magmortar
Togekiss
Yanmega
Leafeon
Glaceon
Gliscor
Mamoswine
Porygon-Z
Gallade
GalladeMega Gallade
Probopass
Dusknoir
Froslass
Rotom
RotomHeat Rotom
RotomWash Rotom
RotomFrost Rotom
RotomFan Rotom
RotomMow Rotom
Uxie
Mesprit
Azelf
Dialga
Palkia
Heatran
Regigigas
GiratinaAltered Forme
GiratinaOrigin Forme
Cresselia
Phione
Manaphy
Darkrai
ShayminLand Forme
ShayminSky Forme
Arceus
Victini
Snivy
Servine
Serperior
Tepig
Pignite
Emboar
Oshawott
Dewott
Samurott
Patrat
Watchog
Lillipup
Herdier
Stoutland
Purrloin
Liepard
Pansage
Simisage
Pansear
Simisear
Panpour
Simipour
Munna
Musharna
Pidove
Tranquill
Unfezant
Blitzle
Zebstrika
Roggenrola
Boldore
Gigalith
Woobat
Swoobat
Drilbur
Excadrill
Audino
AudinoMega Audino
Timburr
Gurdurr
Conkeldurr
Tympole
Palpitoad
Seismitoad
Throh
Sawk
Sewaddle
Swadloon
Leavanny
Venipede
Whirlipede
Scolipede
Cottonee
Whimsicott
Petilil
Lilligant
Basculin
Sandile
Krokorok
Krookodile
Darumaka
DarmanitanStandard Mode
DarmanitanZen Mode
Maractus
Dwebble
Crustle
Scraggy
Scrafty
Sigilyph
Yamask
Cofagrigus
Tirtouga
Carracosta
Archen
Archeops
Trubbish
Garbodor
Zorua
Zoroark
Minccino
Cinccino
Gothita
Gothorita
Gothitelle
Solosis
Duosion
Reuniclus
Ducklett
Swanna
Vanillite
Vanillish
Vanilluxe
Deerling
Sawsbuck
Emolga
Karrablast
Escavalier
Foongus
Amoonguss
Frillish
Jellicent
Alomomola
Joltik
Galvantula
Ferroseed
Ferrothorn
Klink
Klang
Klinklang
Tynamo
Eelektrik
Eelektross
Elgyem
Beheeyem
Litwick
Lampent
Chandelure
Axew
Fraxure
Haxorus
Cubchoo
Beartic
Cryogonal
Shelmet
Accelgor
Stunfisk
Mienfoo
Mienshao
Druddigon
Golett
Golurk
Pawniard
Bisharp
Bouffalant
Rufflet
Braviary
Vullaby
Mandibuzz
Heatmor
Durant
Deino
Zweilous
Hydreigon
Larvesta
Volcarona
Cobalion
Terrakion
Virizion
TornadusIncarnate Forme
TornadusTherian Forme
ThundurusIncarnate Forme
ThundurusTherian Forme
Reshiram
Zekrom
LandorusIncarnate Forme
LandorusTherian Forme
Kyurem
KyuremBlack Kyurem
KyuremWhite Kyurem
KeldeoOrdinary Forme
KeldeoResolute Forme
MeloettaAria Forme
MeloettaPirouette Forme
Genesect
Chespin
Quilladin
Chesnaught
Fennekin
Braixen
Delphox
Froakie
Frogadier
Greninja
Bunnelby
Diggersby
Fletchling
Fletchinder
Talonflame
Scatterbug
Spewpa
Vivillon
Litleo
Pyroar
FlabÃ©bÃ©
Floette
Florges
Skiddo
Gogoat
Pancham
Pangoro
Furfrou
Espurr
MeowsticMale
MeowsticFemale
Honedge
Doublade
AegislashBlade Forme
AegislashShield Forme
Spritzee
Aromatisse
Swirlix
Slurpuff
Inkay
Malamar
Binacle
Barbaracle
Skrelp
Dragalge
Clauncher
Clawitzer
Helioptile
Heliolisk
Tyrunt
Tyrantrum
Amaura
Aurorus
Sylveon
Hawlucha
Dedenne
Carbink
Goomy
Sliggoo
Goodra
Klefki
Phantump
Trevenant
PumpkabooAverage Size
PumpkabooSmall Size
PumpkabooLarge Size
PumpkabooSuper Size
GourgeistAverage Size
GourgeistSmall Size
GourgeistLarge Size
GourgeistSuper Size
Bergmite
Avalugg
Noibat
Noivern
Xerneas
Yveltal
Zygarde50% Forme
Diancie
DiancieMega Diancie
HoopaHoopa Confined
HoopaHoopa Unbound
Volcanion

In [37]:
# GET SPECIFIC ELEMENT WITH AN CONDITION USING LOC[] FUNCTION

df.loc[df['Type2']=='Poison']

,Num,Name,Type1,Type2,HP,Attack,Defense,SpAtk,SpDef,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
53,48,Venonat,Bug,Poison,60,55,50,40,55,45,1,False
54,49,Venomoth,Bug,Poison,70,65,60,90,75,90,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
78,72,Tentacool,Water,Poison,40,40,35,50,100,70,1,False
79,73,Tentacruel,Water,Poison,80,70,65,80,120,100,1,False
99,92,Gastly,Ghost,Poison,30,35,30,100,35,80,1,False
100,93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False
182,168,Ariados,Bug,Poison,70,90,70,60,60,40,2,False
227,211,Qwilfish,Water,Poison,65,95,75,55,55,85,2,False
292,269,Dustox,Bug,Poison,60,50,70,50,90,65,3,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
604,544,Whirlipede,Bug,Poison,40,55,99,40,79,47,5,False
605,545,Scolipede,Bug,Poison,60,100,89,55,69,112,5,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

In [41]:
df.loc[df['Attack']>150]

,Num,Name,Type1,Type2,HP,Attack,Defense,SpAtk,SpDef,Speed,Generation,Legendary
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
313,289,Slaking,Normal,NaN,150,160,100,95,65,100,3,False
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True
454,409,Rampardos,Rock,NaN,97,165,60,65,50,58,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False
543,486,Regigigas,Normal,NaN,110,160,110,80,110,100,4,True
711,646,KyuremBlack Kyurem,Dragon,Ice,125,170,100,120,90,95,5,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True

In [48]:
((df['Attack']>=50) & (df['HP']>=50))[1:20]

1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9     False
10     True
11     True
12     True
13    False
14    False
15    False
16    False
17    False
18     True
19     True
dtype: bool

In [49]:
# DESCRIBE GIVES THE ALL HIGH LEVEL STATISTICS VALUE

df.describe()

,Num,HP,Attack,Defense,SpAtk,SpDef,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [103]:
# WE CAN THE ELEMENTS ( NUMERICAL OR NOT ) IN BOTH ASCENDING OR DESCENDING ORDER

df.sort_values('Name', ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True,600
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False,420
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False,245
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False,330
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False,510
...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False,565
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False,465
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False,310
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False,594
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False,494

In [105]:
df.sort_values(['Attack', 'HP'], ascending=[0,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True,780
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False,600
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True,780
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True,770
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True,600
...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False,540
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False,200
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False,505
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False,450
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False,220

In [59]:
df.head()

,Num,Name,Type1,Type2,HP,Attack,Defense,SpAtk,SpDef,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [82]:
# SHIFTING COLUMN TO DESIRED LOCATION----- HERE WE ARE SHIFTING 'TOTAL' COLUMN TO LEFT OF GENERATION COLUMN

cols = list(df.columns)
df= df[ cols[0:4] + [cols[-1]] + cols[4:6] ]
df.head()

,Num,Name,Type1,Type2,Legendary,Total,Total,Total,Total
0,1,Bulbasaur,Grass,Poison,False,328.0,328.0,328.0,328.0
1,2,Ivysaur,Grass,Poison,False,415.0,415.0,415.0,415.0
2,3,Venusaur,Grass,Poison,False,535.0,535.0,535.0,535.0
3,3,VenusaurMega Venusaur,Grass,Poison,False,635.0,635.0,635.0,635.0
4,4,Charmander,Fire,NaN,False,319.0,319.0,319.0,319.0

In [ ]:
# MODIFYING DATAFRAME -- ADDING VALUES

# 1ST WAY
'''
df['Total']=df['HP']+df['Attack']+df['Defense']+df['SpAtk']+df['SpDef']+df['Speed']
'''
# 2ND WAY

df['Total']= df.iloc[:, 4:10].sum(axis=1)

# DROPPING THOSE USED COLUMNS AFTER ADDITION

df = df.drop(columns=['Attack', 'HP', 'SpAtk', 'SpDef', 'Speed'])
df.head()

In [88]:
df=df1

In [89]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [91]:
df['Total']=df.iloc[:, 4:10].sum(axis=1)
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [93]:
cols=list(df.columns)
df[cols[0:4] + [cols[-1]] + cols[4:12]]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [101]:
# SAVE A CSV FILE

df.to_csv('New_Pokemon_data.csv', index=False)

# SAVE TO A TXT FILE

df.to_csv('New_Poke_Text.txt', index=False, sep='\t')

In [109]:
#  .LOC CONDITION CHECKING OR FILTERING DATA


df.loc[(df['Type 1']=='Fire') & (df['Attack']>=100) & (df['Defense']>=75)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False,555
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True,580
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True,580
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,630
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False,560
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [123]:
New_df=df.loc[(df['Type 1']=='Fire')  | (df['Type 2']=='Flying') | (df['Attack']>=150)]

In [124]:
New_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,534
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,701,Hawlucha,Fighting,Flying,78,92,75,74,63,118,6,False,500
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True,680
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [125]:
New_df.to_csv('filtered.csv', index=False, sep='\t')

In [131]:
# RESETTING THE INDEX OF NEW DATAFRAME

New_df.reset_index(drop=True, inplace=True)
New_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
1,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
2,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,534
3,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
4,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,701,Hawlucha,Fighting,Flying,78,92,75,74,63,118,6,False,500
164,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True,680
165,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
166,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
167,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [136]:
# CHECKING FOR SPECIFIC STRINGS IN COLUMNS OF DATA

df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False,630
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False,495
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False,590
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False,590
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False,600
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,1,False,590
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False,640
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False,615
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True,780
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True,780
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False,525
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,2,False,610
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,2,False,610
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False,600
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False,600
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,2,False,600
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False,700
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False,630
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,630
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,3,False,635
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3,False,618
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,3,False,480
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,3,False,480
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False,630
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,3,False,510
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,3,False,575
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,3,False,560
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False,560
366,334,AltariaMega Altaria,Dragon,Fairy,75,110,110,110,105,80,3,False,590
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False,555
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False,565
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,3,False,580
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,3,False,700
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,3,False,700
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,3,True,700
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,3,True,700
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True,780
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,4,False,580
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,4,False,700
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,4,False,625
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False,594
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False,618
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,5,False,545
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700

In [138]:
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True,600
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [134]:
import re

In [141]:
# CHECKING STAING CONTAINING IN COLUMNS

df.loc[df['Type 1'].str.contains('Grass|Fire', regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False,369
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,507
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [149]:
# WE CAN USE FLAGS TO IGNORE CASE SENSITIVITY ( CAPITAL_LETTER = small letter)

df.dropna(subset=['Type 2'], inplace=True)

df.loc[df['Type 2'].str.contains('water|poison' , regex=True, flags=re.I)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False,195
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False,205
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False,395
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False,495
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False,320
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False,395
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,490
53,48,Venonat,Bug,Poison,60,55,50,40,55,45,1,False,305
54,49,Venomoth,Bug,Poison,70,65,60,90,75,90,1,False,450
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False,300
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False,390
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False,490
78,72,Tentacool,Water,Poison,40,40,35,50,100,70,1,False,335
79,73,Tentacruel,Water,Poison,80,70,65,80,120,100,1,False,515
99,92,Gastly,Ghost,Poison,30,35,30,100,35,80,1,False,310
100,93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,False,405
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False,500
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False,600
149,138,Omanyte,Rock,Water,35,40,100,90,55,35,1,False,355
150,139,Omastar,Rock,Water,70,60,125,115,70,55,1,False,495
151,140,Kabuto,Rock,Water,30,80,90,55,45,55,1,False,355
152,141,Kabutops,Rock,Water,60,115,105,65,70,80,1,False,495
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False,250
182,168,Ariados,Bug,Poison,70,90,70,60,60,40,2,False,390
227,211,Qwilfish,Water,Poison,65,95,75,55,55,85,2,False,430
292,269,Dustox,Bug,Poison,60,50,70,50,90,65,3,False,385
307,283,Surskit,Bug,Water,40,30,32,50,52,65,3,False,269
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False,400
398,363,Spheal,Ice,Water,70,40,50,55,50,25,3,False,290
399,364,Sealeo,Ice,Water,90,60,70,75,70,45,3,False,410
400,365,Walrein,Ice,Water,110,80,90,95,90,65,3,False,530
445,400,Bibarel,Normal,Water,79,85,60,55,60,71,4,False,410
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False,280
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False,515
533,479,RotomWash Rotom,Electric,Water,50,65,107,105,107,86,4,False,520
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False,260
604,544,Whirlipede,Bug,Poison,40,55,99,40,79,47,5,False,360
605,545,Scolipede,Bug,Poison,60,100,89,55,69,112,5,False,485
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False,294
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False,464
758,688,Binacle,Rock,Water,42,52,67,39,56,50,6,False,306
759,689,Barbaracle,Rock,Water,72,105,115,54,86,68,6,False,500
760,690,Skrelp,Poison,Water,50,60,60,60,60,30,6,False,320
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [150]:
# CHECKING THE COLUMNS IF ANY NAME STARTS WITH SPECIFIC STRING NAME LIKE PI, SE, ETC 
#  ^x THIS SIGN MEANS THE WORD WIL BE STARTING FROM x 
#  * MEANS ZERO OR MORE
#  ^pi[a-z]*  MEANS STARTING FROM PI THEN NEXT LETTERS CAN BE BETWEEN A TO Z AND ZERO OR MORE WORD CAN COME AFTER PI
# IF WE DON'T GIVE ^ THEN THAT WILL FIND 'PI' ANYWHERE IN THE NAME & IF WE DON'T GIVE '*' THEN IT WILL ONLY GET PI NOT ANYTHING COMES AFTER THAT


df.loc[df['Name'].str.contains('^pi[a-z]*' , flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,264

In [154]:
df.loc[df['Name'].str.contains('pi[a-z]*' , flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False,390
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False,250
202,187,Hoppip,Grass,Flying,35,35,40,35,55,50,2,False,250
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
266,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False,410
390,357,Tropius,Grass,Flying,99,68,83,72,87,51,3,False,460
463,416,Vespiquen,Bug,Flying,70,80,102,80,102,40,4,False,474
490,442,Spiritomb,Ghost,Dark,50,92,108,92,108,35,4,False,485
501,451,Skorupi,Poison,Bug,40,50,90,30,55,65,4,False,330
502,452,Drapion,Poison,Dark,70,90,110,60,75,95,4,False,500
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,264
596,536,Palpitoad,Water,Ground,75,65,55,65,55,69,5,False,384
716,648,MeloettaPirouette Forme,Normal,Fighting,100,128,90,77,77,128,5,False,600

In [155]:
df.loc[df['Name'].str.contains('^pi[a-z]' , flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,264

In [156]:
df.loc[df['Name'].str.contains('^pi' , flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,264

In [162]:
df.loc[df['Type 2']=='Poison', 'Type 2']='Venom'
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Venom,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Venom,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Venom,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Venom,80,100,123,122,120,80,1,False,625
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,534
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600